version: 2.1
orbs:
  codecov: codecov/codecov@3.2.5
  node: circleci/node@5.0.2
jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - run: |
          echo 'Install NPM'
          sudo npm install -g npm@latest
          sudo npm install -g codecov
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run: |
          echo 'Test Coverage'
          npm run test:coverage
      - run:
          name: Create shared coverage outputs folder
          command: mkdir -p /tmp/coverage
      - run: npm run test:coverage
      - run:
          name: Save coverage
          command: |
            cp coverage/coverage-final.json /tmp/coverage/coverage.json
      - persist_to_workspace:
          root: /tmp/coverage
          paths:
            - coverage.json
  codecov-job:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: /tmp/coverage
      - codecov/upload:
          file: '/tmp/coverage/coverage.json'
workflows:
  jobs-workflow:
    jobs:
      - codecov-job:
          requires:
            - test
      - test
